apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        # this name is only important for logging purposes
        - name: auth
          # image: us.gcr.io/ticketing-dev-392021/auth
          image: quanological/auth
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
   app: auth
  ports:
   - name: auth
     protocol: TCP
     port: 3000
     targetPort: 3000