# This is a basic workflow that is manually triggered

name: tests-payments

on:
  pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - run: cd payments && npm install && npm run test:ci
